server:
  port: 9090

---
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/

---
spring:
  mvc:
    view:
     suffix: .jsp
---
myqueue: spring-study
---
spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672